"""empty message

Revision ID: 2a0ee3ae50c8
Revises: 5ed5d3f8bae8
Create Date: 2021-05-20 22:38:14.594832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0ee3ae50c8'
down_revision = '5ed5d3f8bae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('essays', sa.Text(), nullable=True),
    sa.Column('url_link', sa.Text(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('keyword', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('essay')
    # ### end Alembic commands ###
